Repository MicrosoftDocs/dynamics365smb-devitpro-pb, pull requests merged in 2022-05, with the labels that each got.

#2332 20.1
  dev-itpro/developer/readiness/readiness-ready-to-go.md
  dev-itpro/whatsnew/whatsnew-update-20.1.md
Labels: internal

#2331 Update migrate-dynamics-gp.md
  dev-itpro/administration/migrate-dynamics-gp.md
Labels: internal

#2334 20.1
  dev-itpro/whatsnew/whatsnew-update-20.1.md
Labels: internal

#2338 duplicate versions removed
  dev-itpro/administration/version-numbers.md
Labels: bug

#2243 Update optimize-sql-al-Database-methods-and-performance-on-server.md
  dev-itpro/administration/optimize-sql-al-Database-methods-and-performance-on-server.md
Labels: enhancement
